name: Push Flatpak Update
on:
    workflow_dispatch:
        inputs:
            commit:
                description: Commit pushed
                type: string
                required: true

permissions:
    actions: write

jobs:
    push:
        runs-on: ubuntu-latest

        steps:
          - name: Start Workflow
            uses: convictional/trigger-workflow-and-wait@v1.6.5
            with:
                owner: HighKingofMelons
                repo: flatpak-pages-repo
                workflow_file_name: update-repo.yml
                github_token: ${{ secrets.PAT }}
                #github_user: ${{ github.repositoryOwner }}
                client_payload: '{"repo":"${{ github.repository }}", "commit":"${{ inputs.commit }}","manifest":"org.flatpak.qtdemo.json"}'
